### ISSUE TITLE
React & Redux group project: set up your Kanban board

### ISSUE THREAD

**Issue by mrcbq** [mrcbq/space-travelers-capstone#25]
Hello, my partner @theresetuyi  and I did the following:

- [x] Create an empty repository for our group project. this is the Link: 
- https://github.com/mrcbq/space-travelers-capstone

- Note: for this capstone, we are only two theddy and I.

- [x] Follow the steps described in [curriculum-tools-copy-projects](https://github.com/microverseinc/curriculum-tools-copy-projects) in order to copy the [[TEMPLATE] React Group Project](https://github.com/microverseinc/curriculum-react-redux/projects/1) board.
- [x] Open the GitHub project (Kanban board) in our team repo.
- [x] Make sure that in the card titles, we can see categories: Setup, Fetch data, Lists render, Actions, Conditional components, and Filters.
- [x] Make sure that each card starts with [Xpt] - that number indicates the number of points that shows how complex the task is. 1 point = 1 hour of work.
- [x] We remove all cards with Team3 in the title.
- [x] Each team member should assign themselves to the cards from all categories (and time estimate distributions should be fair - no single person should be doing all of the most time-consuming tasks).
- [x] All cards on our  Kanban board have assignees.
- [x] [Open a new issue in your repository](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-an-issue).
- [x] Paste a link to your GitHub project in its description.
- [x] Add a note telling the reviewer how many people there are on your team.

**Comment by ShadyShawkat** [comment]
## Hi Team, 

Your project is complete!  There is nothing else to say :shipit: 
Congratulations! 🎉 

![Image](https://media.giphy.com/media/jJQC2puVZpTMO4vUs0/giphy.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
